services:
  url-press-php:
    build:
      context: .
    container_name: url-press-php
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    command: php artisan serve --host 0.0.0.0 --port 8080

  url-press-postgres:
    image: postgres:17.5-alpine3.22
    container_name: url-press-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./storage/.db:/var/lib/postgresql/data
